base_model: mistralai/Mistral-7B-v0.3
merge_method: ties
models:
- model: Qwen/Qwen2-7B-Instruct
  parameters:
    density: 0.5
    weight: 0.5
- model: NousResearch/Hermes-2-Pro-Llama-3-8B
  parameters:
    density: 0.5
    weight: 0.5
